### PR TITLE
Add false positive/negative unit tests for ml_api

### PR DESCRIPTION
**Pull request by smartin015**
This is a basic unit test framework intended to shake out bugs in ml_api model initialization, dependencies, and prediction behavior. I consider it to be prep work for #552 and submission of changes to support newer Jetson Nano OS images.

Failure images can be added at `ml_api/tests/failure/*.png` and "non-failure" images at `ml_api/nofailure/*.png` and will show up as unit tests with no additional configuration needed.

Also made some changes to `model_development.md` to introduce the tests and make another shell command easier to use.

I've confirmed this works on my linux workstation (not just my heavily-modded Jetson Nano dev machine). On the workstation it runs in around 4.7 seconds.

### CODE REVIEW

**Comment by kennethjiang** [comment]
Thanks @smartin015 for this PR. However, please consider closing this PR or rewrite it.

Automated tests, including unit test and integration test, is supposed to test the code, not the environments. Your PR does the opposite: it tests the environments, not the code.

I'm also a firm believer that we should not add code that are not regularly exercised. Now that your environments are setup correctly, there is no point for you to run this test regularly. Neither will I or other developers working on this code base until someone else join the ML side of the development, which rarely happens. Unexercised code will be stale and become our liability to carry along, which probably doesn't matter much for companies with deep pocket and a lot developers, but will slow down a tiny team like TSD.

My suggestion is to close this PR. We should address the root cause if users routinely run into environmental problems like you did. An alternative is to have a command line that's similar to `python -m test_image ./img_with_failures.jpg` and add the instructions in `model_development.md`.

**Comment by smartin015** [comment]
> Thanks @smartin015 for this PR. However, please consider closing this PR or rewriting it.
> 
> Automated tests, including unit test and integration test, is supposed to test the code, not the environments. Your PR does the opposite: it tests the environments, not the code.

I'm inclined to disagree - as I see it, this tests the "unit" which is the detection model handler. Having tests like this would've shaved a week or so off my investigation time as I edited the code behind how `/p/?img=` is handled. Perhaps you see the model as the environment because you aren't regularly working on it, whereas I've been poking at it since early January :)

In the end though, you're the gatekeeper and I understand you're making decisions for the benefit of all.

> I'm also a firm believer that we should not add code that are not regularly exercised. Now that your environments are setup correctly, there is no point for you to run this test regularly. Neither will I or other developers working on this code base until someone else join the ML side of the development, which rarely happens. Unexercised code will be stale and become our liability to carry along, which probably doesn't matter much for companies with deep pocket and a lot developers, but will slow down a tiny team like TSD.

I concur, following YAGNI is important to reduce technical debt... I guess I drank the kool-aid a bit in thinking there was actually ML development planned, in which case this would've been more useful. I wasn't aware you had no ML developers.

I was considering trying my hand at #508, where this would also come in handy. But I suppose I can just keep it in my fork for my own development purposes.

> My suggestion is to close this PR. We should address the root cause if users routinely run into environmental problems like you did. An alternative is to have a command line that's similar to `python -m test_image ./img_with_failures.jpg` and add the instructions in `model_development.md`.

Would you accept a PR containing a single failure & a single success image, with amendments to `model_development.md`?

**Comment by kennethjiang** [comment]
This repo is web dev repo, not an ML dev repo. We have a very messy ML dev pipeline (it's not a repo as it contains GBs of training data) that we can't open source because of the data privacy concerns.

> Would you accept a PR containing a single failure & a single success image, with amendments to model_development.md?
I can see how this provides a good way for new developers to quickly test their env. How about a script to make `python -m lib.detection_model xxx` more user-friendly by adding a shell script and/or help messages?

**Comment by smartin015** [comment]
Sounds like a plan. I'll close this PR and contribute something after the dust settles on my changes to rely more on darknet python code and eliminate `detection_model.py`.

I do hope that as things progress, more of the training pipeline itself (not the data - understood that data privacy is important, but more the data preprocessing, analysis/stats generation, training & export code) could be made open source, as I find the ML part of this project fascinating. From what you've told me though, that's probably a pretty significant effort. 

FWIW I'd be open to helping with some of that work, but I won't feel bad if you'd prefer not to deal with the privacy concerns / NDAs etc.

**Comment by kennethjiang** [comment]
@smartin015 Will love to get your help on the ML part. And yes I do need you to sign a NDA for that. Feel free to email support@thespaghettidetective.com to kick off the process.

**Pull request closed without merging**
