### PR TITLE
Allow users to change their password

### LINKED ISSUE #9: change password in preferences

### PR DESCRIPTION
**Pull request by wwsean08**
This fixes #9 by allowing users to change their passwords.  I've limited the URL to show up for regular (non-social) accounts, though allauth does seem to support social accounts setting up passwords, I just haven't done enough investigating to understand the implications of that.

Testing done:
I spun up a server on DigitalOcean, got a cert from LetsEncrypt, and setup google's social account backend to verify the following things:
* That the option to change your password does not show for socialaccounts
* The option to change your password shows for regular accounts
* I was able to change my password successfully with a regular account

### CODE REVIEW

**Comment by kennethjiang** [comment]
Sorry @wwsean08 this PR completely slipped through my task tracking system. Will test it the first thing tomorrow.

**Comment by kennethjiang** [comment]
@wwsean08 My apology again for missing your PR.

Your PR functions correctly. 

The only thing is that if I enter the wrong current password, it doesn't show any error message.

Hope it's a quick fix to add/turn on the error message on wrong password?

**Comment by wwsean08** [comment]
I'll try to figure that out this weekend, been busy teaching myself angular the last week or so, so haven't had time to play around with python.

**Comment by wwsean08** [comment]
Going to open up a new PR because I'm having trouble getting this rebased properly due to upstream CSS changes and i'm tired of fighting with git today.

**Comment by kennethjiang** [comment]
Sorry that the recent change created problems for your PR.

Not sure if it was clear to you - `app.css` is derived from `.scss` files, primarily `main.scss`. So you don't want to change `app.css` directly. Instead, you just run `yarn build` in folder `web` to build it.

Ideally we shouldn't commit `app.css` to git and only have it generated at build time. But we haven't got around to that yet.

**Comment by wwsean08** [comment]
ok Will fix that in my other PR

**Pull request closed without merging**
